export enum JobType {
  DataEntryAndBackOffice = 18,
  MediaEntertainment = 19,
  SalesAndMarketting = 20,
  BPOAndTelecaller = 21,
  HealthCareAndHospitility = 22,
  OfficeAssistant = 23,
  RetailAndStore = 24,
  DeliveryAndCollection = 25,
  TeacherAndTrainer = 26,
  CookAndDriverAndSecurity = 27,
  ReceptionistAndFrontOffice = 28,
  OperatorAndTechnician = 29,
  ITAndSoftware = 30,
  HotelAndTravel = 31,
  FinanceAndAccounting = 32,
  Others = 33,
}
